### ISSUE TITLE
The bot's AIML module is not handling conversations properly

### ISSUE THREAD

**Issue by Thielak** [JustArchi/ArchiBoT#64]
Looking into #63 , code for the rest of the "knock knock" joke is present in that.aiml.

[Line 101:
`<category><pattern>*</pattern><that>WHO IS THERE</that>
<template><star/> who?</template>
</category>`](https://github.com/JustArchi/ArchiBoT/blob/master/AIML/lib/aiml/that.aiml#L101-L102)
[Line 80:
`<category><pattern>*</pattern><that>* WHO</that>
<template><srai>LOL</srai></template>
</category>`](https://github.com/JustArchi/ArchiBoT/blob/master/AIML/lib/aiml/that.aiml#L80-L81)

I'm not sure if the bot is not properly using the content in the other .aiml files or if your implementation lacks the ability of using the aiml tag `<that>`  to handle multi-message conversations with the bot.

### Expected result:
> Human: knock knock 
ArchiBoT: who is there?
Human: Archi
ArchiBoT: Archi who?
Human: I didn't think of a joke
ArchiBoT: Hahahahaha!

### Actual result:
> Human: knock knock
ArchiBoT: who is there
Human: Archi
ArchiBoT: `<unrelated answer>`

**Comment by JustArchi** [comment]
Fixed, thanks for report!
